#!/usr/bin/env bash
#
# Preprocess all 7 datasets from the Google-Drive data layout into E2Efold's
# `RNA_SS_data` pickle format.
#
# Input:   $E2EFOLD_DATA_ROOT/  (set by first argument, default: /home/xiwang/project/develop/data)
#   ├── rivals/                 (TrainSetA-addss.pkl, TestSetA-addss.pkl, TestSetB-addss.pkl)
#   ├── mxfold2/                (TR0/VL0/TS0-canonicals.pkl, RNAStrAlign600-train.pkl,
#   │                            archiveII.pkl, bpRNAnew.pkl)
#   ├── all_data_1024_0.75/     (train.pkl, valid.pkl, test.pkl)  — UniRNA-SS
#   └── ipkont/                 (bpRNA-TR0.pkl, bpRNA-PK-TS0-1K.pkl)
#
# Output: data/<dataset_name>/{train,val,test}.pickle
#
# Usage:
#   bash scripts/preprocess_all.sh [DATA_ROOT]
#
set -euo pipefail

DATA_ROOT="${1:-${E2EFOLD_DATA_ROOT:-/home/xiwang/project/develop/data}}"
export E2EFOLD_DATA_ROOT="$DATA_ROOT"

cd "$(dirname "$0")/.."

echo "============================================================"
echo "Preprocessing all datasets"
echo "  DATA_ROOT = $DATA_ROOT"
echo "============================================================"

python3 data/preprocess_rnastralign_from_mxfold2.py
python3 data/preprocess_rivals.py
python3 data/preprocess_bprna.py
python3 data/preprocess_unirna_ss.py
python3 data/preprocess_ipknot.py
python3 data/preprocess_archiveii_full.py
python3 data/preprocess_bprna_new.py

# ArchiveII test.pickle is generated by preprocess_archiveii_full.py (test ≤600bp subset)
# For full compatibility with experiment_archiveii_full, copy it if archiveii_short exists
if [ -d data/archiveii_short ] && [ -f data/archiveii_short/test.pickle ]; then
    cp data/archiveii_short/test.pickle data/archiveii_full/test.pickle
fi

echo
echo "All datasets preprocessed successfully. Output under ./data/"
ls -la data/ | grep -v '^\.\|^total\|preprocess_'
